Bump python-on-whales from 0.53.0 to 0.63.0 (#7426)
Bumps
[python-on-whales](https://github.com/gabrieldemarmiesse/python-on-whales)
from 0.53.0 to 0.63.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/gabrieldemarmiesse/python-on-whales/releases">python-on-whales's
releases</a>.</em></p>
<blockquote>
<h2>v0.63.0</h2>
<h2>What's Changed</h2>
<ul>
<li>456 use stdin to log in by <a
href="https://github.com/zimmdi"><code>@​zimmdi</code></a> in <a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/459">gabrieldemarmiesse/python-on-whales#459</a></li>
<li>439 no support for buildx build build context by <a
href="https://github.com/bigcat2014"><code>@​bigcat2014</code></a> in <a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/440">gabrieldemarmiesse/python-on-whales#440</a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a href="https://github.com/zimmdi"><code>@​zimmdi</code></a> made
their first contribution in <a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/459">gabrieldemarmiesse/python-on-whales#459</a></li>
<li><a
href="https://github.com/bigcat2014"><code>@​bigcat2014</code></a> made
their first contribution in <a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/440">gabrieldemarmiesse/python-on-whales#440</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/gabrieldemarmiesse/python-on-whales/compare/v0.62.0...v0.63.0">https://github.com/gabrieldemarmiesse/python-on-whales/compare/v0.62.0...v0.63.0</a></p>
<h2>v0.62.0</h2>
<h2>What's Changed</h2>
<ul>
<li>Fix: fix the gh-pages ci by <a
href="https://github.com/kclamalex"><code>@​kclamalex</code></a> in <a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/449">gabrieldemarmiesse/python-on-whales#449</a></li>
<li>Additional Docker Compose Run Flags by <a
href="https://github.com/ethanleifer"><code>@​ethanleifer</code></a> in
<a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/443">gabrieldemarmiesse/python-on-whales#443</a></li>
<li>Feat: Add --no-attach option for docker.compose.up by <a
href="https://github.com/kclamalex"><code>@​kclamalex</code></a> in <a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/451">gabrieldemarmiesse/python-on-whales#451</a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a
href="https://github.com/ethanleifer"><code>@​ethanleifer</code></a>
made their first contribution in <a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/443">gabrieldemarmiesse/python-on-whales#443</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/gabrieldemarmiesse/python-on-whales/compare/v0.61.0...v0.62.0">https://github.com/gabrieldemarmiesse/python-on-whales/compare/v0.61.0...v0.62.0</a></p>
<h2>v0.61.0</h2>
<p><strong>Installing this version requires python 3.8 or above. The end
of life of python 3.7 is the 27 of june, so if you are still using it,
please upgrade!</strong></p>
<h2>What's Changed</h2>
<ul>
<li>:up: Bump minimum python version to 3.8 by <a
href="https://github.com/gabrieldemarmiesse"><code>@​gabrieldemarmiesse</code></a>
in <a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/431">gabrieldemarmiesse/python-on-whales#431</a></li>
<li>:sparkles: Add more precise type hints for filters in docker.ps() by
<a
href="https://github.com/gabrieldemarmiesse"><code>@​gabrieldemarmiesse</code></a>
in <a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/432">gabrieldemarmiesse/python-on-whales#432</a></li>
<li>:sparkles: Clarify type for buildx progress by <a
href="https://github.com/gabrieldemarmiesse"><code>@​gabrieldemarmiesse</code></a>
in <a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/435">gabrieldemarmiesse/python-on-whales#435</a></li>
<li>Support passing signals as integers (or signal.Signals enum
instances) by <a
href="https://github.com/LewisGaul"><code>@​LewisGaul</code></a> in <a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/441">gabrieldemarmiesse/python-on-whales#441</a></li>
<li>Allow container selection in 'docker stats' by <a
href="https://github.com/MisterOwlPT"><code>@​MisterOwlPT</code></a> in
<a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/447">gabrieldemarmiesse/python-on-whales#447</a></li>
<li>Use mkdocstrings to generate documentation by <a
href="https://github.com/kclamalex"><code>@​kclamalex</code></a> in <a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/444">gabrieldemarmiesse/python-on-whales#444</a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a href="https://github.com/kclamalex"><code>@​kclamalex</code></a>
made their first contribution in <a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/444">gabrieldemarmiesse/python-on-whales#444</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/gabrieldemarmiesse/python-on-whales/compare/v0.60.1...v0.61.0">https://github.com/gabrieldemarmiesse/python-on-whales/compare/v0.60.1...v0.61.0</a></p>
<h2>v0.60.1</h2>
<h2>What's Changed</h2>
<ul>
<li>:bug: Prevent the user from installing pydantic v2 by <a
href="https://github.com/gabrieldemarmiesse"><code>@​gabrieldemarmiesse</code></a>
in <a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/430">gabrieldemarmiesse/python-on-whales#430</a></li>
</ul>
<p>⚠️ Install this release if you get the error <code>AttributeError:
type object 'NetworkIPAM' has no attribute '__fields__'</code>, see <a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/issues/429">#429</a></p>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/gabrieldemarmiesse/python-on-whales/compare/v0.60.0...v0.60.1">https://github.com/gabrieldemarmiesse/python-on-whales/compare/v0.60.0...v0.60.1</a></p>
<h2>v0.60.0</h2>
<h2>What's Changed</h2>
<ul>
<li>Add pull flag to docker compose up by <a
href="https://github.com/John-Vash"><code>@​John-Vash</code></a> in <a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/pull/421">gabrieldemarmiesse/python-on-whales#421</a></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/gabrieldemarmiesse/python-on-whales/commit/ef869fbc5fe751c342487f9e8cb2ace77c0714fd"><code>ef869fb</code></a>
Bump version to 0.63.0</li>
<li><a
href="https://github.com/gabrieldemarmiesse/python-on-whales/commit/9d79f885d28809f59f927097f5cc5b518998920a"><code>9d79f88</code></a>
439 no support for buildx build build context (<a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/issues/440">#440</a>)</li>
<li><a
href="https://github.com/gabrieldemarmiesse/python-on-whales/commit/2a69761e9ec914ded621ca4eee8830a1e4bcf522"><code>2a69761</code></a>
456 use stdin to log in (<a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/issues/459">#459</a>)</li>
<li><a
href="https://github.com/gabrieldemarmiesse/python-on-whales/commit/6549a4f7ffd03d555d2ac661ff7c963863fd1d59"><code>6549a4f</code></a>
Add explicit optional on all models (<a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/issues/454">#454</a>)</li>
<li><a
href="https://github.com/gabrieldemarmiesse/python-on-whales/commit/af04c5de231f586f8a108e55e482a7235c80639d"><code>af04c5d</code></a>
Bump version to 0.62.0</li>
<li><a
href="https://github.com/gabrieldemarmiesse/python-on-whales/commit/08418a476507d2661644d6434d223dce9871c318"><code>08418a4</code></a>
Feat: Add --no-attach option for docker.compose.up (<a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/issues/451">#451</a>)</li>
<li><a
href="https://github.com/gabrieldemarmiesse/python-on-whales/commit/730c48ab1c4d7492fd6339ffafe4286749ad4dc0"><code>730c48a</code></a>
Additional Docker Compose Run Flags (<a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/issues/443">#443</a>)</li>
<li><a
href="https://github.com/gabrieldemarmiesse/python-on-whales/commit/d2d6070f833460d901b2fa95cd1a90152e911e93"><code>d2d6070</code></a>
Fix: fix the gh-pages ci (<a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/issues/449">#449</a>)</li>
<li><a
href="https://github.com/gabrieldemarmiesse/python-on-whales/commit/f3728f5b4b4464c450d32f6726a11531e0158a2e"><code>f3728f5</code></a>
Bump version to 0.61.0</li>
<li><a
href="https://github.com/gabrieldemarmiesse/python-on-whales/commit/da951346b628cb940361beab7ad9923ff6338de6"><code>da95134</code></a>
Use mkdocstrings to generate documentation (<a
href="https://redirect.github.com/gabrieldemarmiesse/python-on-whales/issues/444">#444</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/gabrieldemarmiesse/python-on-whales/compare/v0.53.0...v0.63.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=python-on-whales&package-manager=pip&previous-version=0.53.0&new-version=0.63.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: dependabot[bot] <dependabot[bot]@users.noreply.github.com>